export {default as Header}  from './Header/Header';
export {default as Hero} from './Hero/Hero';
export {default as SpecialMenu} from './SpecialMenu/SpecialMenu';
export {default as AboutUs} from './AboutUs/AboutUs';
export {default as OurMenu} from './OurMenu/OurMenu';
export {default as OurChefs} from './OurChefs/OurChefs';
export {default as KlassyWeek} from './KlassyWeek/KlassyWeek';
export {default as Contact} from './Contact/Contact';
export {default as Footer} from './Footer/Footer';
export {default as MenuReserv } from  './MenuReserv/MenuReserv';